PROGRAM MAIN

    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: SP=>REAL32, DP=>REAL64
    IMPLICIT NONE

    REAL, PARAMETER :: R = 1.0
    INTEGER, PARAMETER :: N = 100000000
    REAL :: PIN, PI
    ! REAL*8 :: PI
    INTEGER :: INS

    REAL, DIMENSION(N) :: RAND_X, RAND_Y

    INTEGER :: I

    CALL RANDOM_NUMBER(RAND_X)
    CALL RANDOM_NUMBER(RAND_Y)

    INS = 0
    DO I = 1, N
        PIN = RAND_X(I)**2 + RAND_Y(I)**2
        IF (PIN <= 1) THEN
            INS = INS + 1 
        END IF
    END DO

    PI = PICALC(INS, N)
    PRINT *, 'PI =', PI

CONTAINS
    PURE FUNCTION PICALC(INPINS, TRIALS) RESULT(RETVAL)
        INTEGER, INTENT(IN) :: INPINS, TRIALS
        REAL :: RETVAL, RATIO
        REAL :: IN_R, N_R

        N_R = REAL(TRIALS)
        IN_R = REAL(INPINS)
        RATIO = IN_R / N_R
        RETVAL = 4 * RATIO

    END FUNCTION PICALC

END PROGRAM